#+title: Apple Cider Doughnuts

Simplified from [[https://smittenkitchen.com/2009/10/apple-cider-doughnuts/][Smitten Kitchen]].

Makes about 20 doughnuts (and holes).

/The dough:/

- 1 c. apple cider
- 3½ c. flour
- 2 tsp. baking powder
- 1 tsp. baking soda
- ½ tsp. ground cinnamon
- ½ tsp. salt
- ⅛ tsp. ground nutmeg
- 4 tbsp. butter (room temperature)
- 1 c. granulated sugar
- 2 large eggs
- ½ c. buttermilk
- Tub of shortening (for frying)

/The glaze (optional):/

- 1 c. confectioners' sugar
- 2 tbsp. apple cider

/The cinnamon sugar (optional):/

- 1 c. granulated sugar
- 1½ tbsp. cinnamon

Reduce the apple cider from 1 c. down to about ¼ c. in a saucepan over medium
heat. Should take 20 minutes or so. Let it cool.

Combine dry ingredients in a bowl. Set aside.

Beat sugar and butter together until smooth. Gradually add eggs, apple cider
reduction, and buttermilk, mixing until combined. Add flour mixture and mix
until the dough comes together.

Line a couple baking sheets with wax paper and sprinkle with flour (the dough is
suprisingly sticky). Flatten the dough until it's about ½" thick. Harden the
dough a little by putting it in the freezer for 20 minutes.

Cut the dough into doughnut shapes---about 3" on the outside and 1" on the
inside. Re-roll the scraps of dough and re-refrigerate them to cut into more
doughnuts.

If making glaze, whisk the confectioners' sugar and cider together. If making
cinnamon sugar, combine those ingredients.

Prep the frying area: stove and pan, draining area with paper towels, topping
tub.

Add shortening to a deep pan to a depth of a couple inches. Attach a candy
thermometer and heat the oil to 350°.

Fry the doughnuts a few at a time until they're golden brown (about 60 seconds),
then flip 'em and fry a bit longer (about 30 seconds). Drain on the paper
towels, then dip the top of the doughnuts into the glaze or cinnamon sugar.
Serve.
