#+title: Beet Juice (Light, Organic)

- two or more Organic Whole Red Beets (root only)
- pinch of organic Cumin or Fennel seeds
- pinch of organic Himalayan Pink Salt 
- Pinch of organic Black Peppercorn (crushed)

Cut the beets up into a few pieces, large enough to retain some of it's juices
during the slow cooking process. Place the beets in a large slow cooker.

Fill the slow cooker with water nearly to the top. Slow cook on normal slow
cooker settings, to your taste preference.

After slow cooking is completed, use the 'keep warm' setting on your slow
cooker to keep the light juice fusion active and warm. 

Scoop the juice out at any time after slow cooking is completed using a ladel.
You can make several glasses of beet juice at a time like this. If you prefer
to put the beet juice in a pitcher and keep it cold in the refrigerator, 
that will be okay.

When the slow cooker is emptied of juice, take the remaining beet slices and
place them into a pot or onto a pan. You can use them for stir fry or soup.

---

Alternate choices of spices can be replaced for taste.
