* Cold Brew Coffee

- 6 oz. coffee, ground coarsely
- 36 oz. cold water (filtered, if possible)

Mix ground coffee and water, stirring to make sure all the grounds get wet.

Let sit on a counter at least overnight (I usually leave it for 24 hours), then
filter through a regular paper filter and refrigerate. I'll often pass the
mixture through a mesh colander before filtering to remove the bulk of the
grounds and avoid clogging the paper filter.

Many folks would describe the resulting strong coffee as "concentrate" and
suggest diluting it with water or milk, but I think it's also great as-is.

The key points here are:

- Use good coffee and either filtered or spring water. It genuinely makes a
  difference.
- Mix at a 6:1 weight ratio of water to coffee. That will seem like /way/ too much
  coffee, but you really do need a lot, and weak cold brew is deeply
  disappointing.
- Use a coarse grind. You might think a finer grind would increase, I don't
  know, /flavor extraction/ or something, but actually the fine particles will
  just pass through the paper filter and leave you with cloudy and unsightly
  coffee that's not appreciably stronger.
