#+title: Lasagna

- 1 box oven-ready lasagna noodles
- 1 c. grated Parmesan

/For the cheese:/

- 16 oz. ricotta
- 8 oz. shredded mozzarella
- 2 eggs

/For the sauce:/

- A few tablespoons of olive oil
- 2-3 cloves of garlic, chopped fine
- 1 white onion, diced
- 1 bell pepper, diced
- 1 zucchini, diced
- 2 carrots, diced
- Box of mushrooms, washed and chopped
- 2 jars of commercial pasta sauce
- Bag of spinach

If you're planning on baking the lasagna immediately after assembling it,
preheat oven to 375°.

Saute the onion, pepper, zucchini, carrots, and garlic in a large saucepan with
the olive oil. Feel free to add some salt and pepper, cracked red pepper, or
oregano to taste. When the vegetables begin to soften add the mushrooms and cook
for another minute or two. Add both jars of pasta sauce and the whole bag of
spinach. Simmer for a few minutes until the spinach wilts.

While the sauce simmers, combine ricotta, mozzarella, and eggs and stir until
well mixed.

In a 13"x9" baking dish, add a ladle-full of sauce, then start layering noodles,
cheese, and sauce until all ingredients have been used up. Top with Parmesan and
cover dish with foil.

You can store this in the fridge for a day or so before baking it. It'll be
colder inside if you do, though, so you'll need to bake it longer to ensure that
the noodles are fully cooked.

If you're baking it immediately after assembly, put it in for 30 minutes. If
it's cold, give it 50--60 minutes.

Remove from oven, remove foil, let cool for a few minutes, and serve.
