#+title: Pulled Noodles

Adapted from Red House Spice https://redhousespice.com/hand-pulled-noodles/

- 250 g all-purpose flour
- pinch of salt
- 125 ml water (half of the all-purpose flour)
- cooking oil - for coating the dough

Mix flour and salt. Add water gradually. Mix with hand until no more loose flour can be seen. Combine and knead briefly into a dough. Leave to rest for 10-15 minutes (covered with wet paper towel).
Knead again for about 2 minutes until very smooth.

Divide the dough into two equal parts. With a rolling pin, flatten each piece into a rectangle shape (about ½ cm thick).
Thoroughly coat each piece with oil then place them on a tray. Cover with cling film then leave to rest for 1.5 hours.

Bring a large pot of water to a full boil. While waiting, cut the dough.

Place one piece of dough on a big board or sheet pan. Cut it into strips for pulling.

Pick up one strip of dough by holding each end gently. Pull towards opposite directions. The movement should be smooth and consistent.

Drop the pulled noodle into boiling water. Repeat the procedure to pull other strips cut from the first piece of dough.

Cook for 2 minutes for the wide noodles (While waiting, cut the second piece of dough into strips.).

Transfer noodles into wok for light stir fry.
