#+title: Spicy Stir-fried Chickpeas

Adapted from [[https://grimgrains.com/site/spicy_stirfry_chickpeas.html][Grim Grains]].

/For the marinade:/

- 15 oz. can of chickpeas
- ⅓ lb. tofu, cubed
- 2 tsp. soy sauce
- 1 tsp. balsamic vinegar
- 1 tbsp. cornstarch or arrowroot powder
- Pinches of salt and pepper

/For the sauce:/

- 1 tbsp. maple syrup
- 1 tbsp. soy sauce
- 2 tbsp. balsamic vinegar
- 1 tbsp. cornstarch or arrowroot powder
- 1 tsp. sesame oil

/For the stirfry:/

- 3 cloves garlic, peeled and diced
- 1 medium carrot, diced
- 2 scallion stalks, sliced fine
- Inch of ginger, peeled and diced
- Several leaves of red cabbage, sliced
- 1 tsp. red pepper flakes
- 1 tsp. ground Sichuan peppercorns
- Pinches of salt and pepper

Combine all marinade ingredients, including the tofu and chickpeas, and
refrigerate overnight (or at least for a few hours).

Combine sauce ingredients in a small bowl.

Drain marinated chickpeas and tofu.

Heat a tablespoon of vegetable oil in a frying pan. Add tofu, chickpeas, carrot,
red cabbage, red pepper flakes, and ground peppercorns. Cook for a minute or
two.

Add ginger, garlic, and scallions. Cook for a few more minutes.

Stir in sauce and cook until thickened.
